In [18]:
from mdp_sequence_reader import MDPSequenceReader
from training_pomdp_util import *
from observable_markov_model import ObservableMarkovModel

In [19]:
# read the sequence
reader = MDPSequenceReader('sample_sequence/o_0_0.txt')
print("Num states: %d" % reader.get_num_states())
print("Num steps: %d" % reader.get_num_steps())

Num states: 8
Num steps: 10000


In [20]:
# get the sequences
observations = reader.get_observation_sequence()
actions = reader.get_action_sequence()

In [21]:
# get the initial model
action_space = [0, 1, 2, 3]   # (up, right, down, left)
num_states = reader.get_num_states()
num_observables = 16   # binary measurements of 4 directions

init_model = initialize_random_pomdp_model(num_states, action_space, num_observables)

In [22]:
model = init_model
for r in range(100):
    alist, c = improve_params(xs=actions, ys=observations, m=model)
    new_model = ObservableMarkovModel(alist, c, model.init)
    
    log_likelihood = get_log_likelihood(make_tableaus(xs=actions, ys=observations, m=new_model))
    print("round=%d, log likelihood=%f" % (r+1, log_likelihood))
    
    model = new_model

round=1, log likelihood=-16633.272283
round=2, log likelihood=-15596.648450
round=3, log likelihood=-13774.092803
round=4, log likelihood=-10723.534703
round=5, log likelihood=-7859.906108
round=6, log likelihood=-6478.890226
round=7, log likelihood=-5616.118622
round=8, log likelihood=-4617.529860
round=9, log likelihood=-3645.438553
round=10, log likelihood=-3205.139141
round=11, log likelihood=-3027.972924
round=12, log likelihood=-2890.285000
round=13, log likelihood=-2826.162681
round=14, log likelihood=-2816.793259
round=15, log likelihood=-2815.372681
round=16, log likelihood=-2813.848106
round=17, log likelihood=-2812.039482
round=18, log likelihood=-2809.895289
round=19, log likelihood=-2807.378357
round=20, log likelihood=-2804.465135
round=21, log likelihood=-2801.144427
round=22, log likelihood=-2797.414035
round=23, log likelihood=-2793.275713
round=24, log likelihood=-2788.730631
round=25, log likelihood=-2783.778151
round=26, log likelihood=-2778.419441
round=27, log lik

KeyboardInterrupt: 

In [ ]:
print(alist, c)

In [31]:
a = np.zeros((3, 5, 7))
print(a[2, :, :])
print('--')
print(a[2:3, :, :])
print('--')
print(a)
a[:, 2, :] = 3
print('--')
print(a)
print('--')
a[2] = 7
print(a)
a[:,:,2] = 9
print('--')
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
--
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
--
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
--
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [3. 3. 3. 3. 3. 3. 3.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [3. 3. 3. 3. 3. 3. 3.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [3. 3. 3. 3. 3. 3. 3.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0.